[package]
name = "tempo"
version = "0.1.0"
authors = ["njwoodge <woodgern@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.9.1"
itertools = "0.9.0"
rand = "0.7.3"
thincollections = "0.5.3"
